# main text of home
name: Matt Radbourne
bio: 'London-based web developer, digital exorcist/UXer and game dev enthusiast.'

# if it's an external image, update below for true
external-image: false
picture: 'assets/images/matt-radbourne_512x512.jpg'

url: http://mradbourne.github.io
# your url: http://USERNAME.github.io

permalink: /blog/:title/

collections:
  projects:
    output: true
  ux_projects:
    output: true
    permalink: /ux/:path/

markdown: kramdown
highlighter: rouge

analytics-google: 'UA-19813149-11'

# if you don't want comments in your posts, set to false
disqus: radbourne

# if you don't have any of social below, comment the line
# facebook: myfacebook
twitter: mradbourne
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
linkedin: in/mradbourne
# youtube: myyoutube
# spotify: myspotify
github: mradbourne
# medium: medium
# email: myemail@gmail.com

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need "about" or "blog", comment them out below
about: true
blog: true

# do you want to show the "read time" of the posts?
read-time: false

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: false

# do you want some animations?
animation: true

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, indigo-gh-pages.zip, Rakefile, screen-shot.png, travis.sh]
